### ISSUE TITLE
Linux Bash : Uptime display promlem

### ISSUE THREAD

**Issue by Habilya** [Habilya/SSH-Welcome-screen#1]
https://github.com/Habilya/SSH-Welcome-screen/blob/c399457f60eca38a8c5121f5cc4051633d9d6722/MOTD.sh#L66

```Bash

uptime | awk -F'( |,|:)+' '{print $6,$7",",$8,"hours,",$9,"minutes."}'
```

This part of the script returns

> Uptime = 2 50, 2 hours, users minutes.

When uptime is less than one day.

**Comment by redpfire** [comment]
Hello, what is exactly that you want to display?
