### ISSUE TITLE
fatal: division by zero attempted

### ISSUE THREAD

**Issue by TeeSee64** [Habilya/SSH-Welcome-screen#20]
I get this error:
awk: cmd. line:1: (FILENAME=- FNR=3) fatal: division by zero attempted

Did everything as discribed and copy paste the MOTD.sh file. Cant figure out what is wrong.

**Comment by Habilya** [comment]
Hello @TeeSee64 , can you post the output of the 
`free -m` 
command?
this will help to reproduce this bug.
Thanks

**Comment by TeeSee64** [comment]
Hi!

This is the output of that command. 

              total        used        free      shared  buff/cache   available
Mem:            975         202         109          34         663         674
Swap:             0           0           0

**Comment by Habilya** [comment]
try the new version.

**Comment by TeeSee64** [comment]
That version works perfect.
thank you so much!!
