### ISSUE TITLE
Linux Bash : Add some comments (Documentation) in the script

### ISSUE THREAD

**Issue by Habilya** [Habilya/SSH-Welcome-screen#22]
Please document the main [MOTD.sh](https://github.com/Habilya/SSH-Welcome-screen/blob/master/SCRIPT/MOTD.sh)
Add the comments directly in the script for better maintainability of the script.

Thanks for your contribution!

**Comment by AlexanderDavid** [comment]
I can take this one

**Comment by Habilya** [comment]
Hello, Feel Free to send in PRS!
